# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/toftul"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/ivan_toftul"

[social.params]
icon = "brand-twitter"


[[social]]
identifier = "google-scholar"
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=N9i1kRgAAAAJ"

[social.params]
icon = "school"


[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/indie314/"

[social.params]
icon = "brand-instagram"